language: ruby
rvm:
  - 2.1.0
bundler_args: --without production

# By default, the build environment will have version 9.1 running already.
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace

script:
  - bundle exec rspec
  - bundle exec rake teaspoon
