language: ruby
rvm:
  - 2.0.0
bundler_args: --without production
addons:
  postgresql: "9.3"
services:
  - postgresql
  
before_install:
  - sudo apt-get update -qq && && sudo apt-get -qq -y upgrade
  - sudo apt-get install -qq build-essential g++ flex bison gperf ruby perl \
      libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
      libpng-dev libjpeg-dev python libx11-dev libxext-dev ttf-mscorefonts-installer
  - git clone --recurse-submodules git://github.com/ariya/phantomjs.git
  - cd phantomjs
  - ./build.py --jobs 1
  
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace

script:
  - bundle exec rspec
  - bundle exec teaspoon

notifications:
  email:
    on_success: always
    on_failure: always